#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: 'projects'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'De Date',   url: 'date'}
- {name: 'Untitled',   url: 'untitled'}


#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://instagram.com/bjarneliv'}
- {icon: 'envelope',  link: 'mailto:mailto:bjarneliv@proton.me'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio for actor Bjarne Liveyns, powered by Jekyll and Github Pages'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'G-N9XEZNRGXX'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
